<a href="https://colab.research.google.com/github/Megha20Mohan/Task-files/blob/main/Numpy_practice_Assignment_2_AM_EN_U4AIE21176.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
myPythonList = [1,9,8,3]
print(myPythonList)

[1, 9, 8, 3]


In [ ]:
numpy_array_from_list = np.array(myPythonList)
numpy_array_from_list

array([1, 9, 8, 3])

In [ ]:
a  = np.array([1,9,8,3])
print(a)

[1 9 8 3]


In [ ]:
x=numpy_array_from_list + 10
print(x)

[11 19 18 13]


In [ ]:
a  = np.array([1,2,3])
print(a.shape)
print(a.dtype)

(3,)
int64


In [ ]:
#### Different type
b  = np.array([1.1,2.0,3.2])
print(b.dtype)

float64


In [ ]:
### 2 dimension
c = np.array([(1,2,3),
              (4,5,6)])
print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
### 3 dimension
d = np.array([
    [[1, 2,3],
        [4, 5, 6]],
    [[7, 8,9],
        [10, 11, 12]]
])
print(d.shape)
(2, 2, 3)
print(d)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
import numpy as np
x=np.zeros((2,2), dtype=np.int16)
print(x)

[[0 0]
 [0 0]]


In [ ]:
import numpy as np
y=np.ones((1,2,3), dtype=np.int16)
print(y.shape)	
print(y)

(1, 2, 3)
[[[1 1 1]
  [1 1 1]]]


In [ ]:
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
e.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
## Horitzontal Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


In [ ]:
## Vertical Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


In [ ]:
## Generate random nmber from normal distribution
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[5.28290621 5.17457341 4.74404582 4.42760485 4.68799262 5.6979259
 4.9610971  5.11162288 5.6597653  4.56200309]


In [ ]:
A = np.matrix(np.ones((4,4)))		
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
np.asarray(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


In [ ]:
np.arange(1, 11)	

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1, 14, 4)	

array([ 1,  5,  9, 13])

In [ ]:
import numpy as np
np.linspace(1.0, 10.0, num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [ ]:
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [ ]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize	

16

In [ ]:
## Slice
import numpy as np
e  = np.array([(4,5,6), (7,8,9)])
print(e)


[[4 5 6]
 [7 8 9]]


In [ ]:
## First column
print('First row:', e[0])

## Second col
print('Second row:', e[1])

First row: [4 5 6]
Second row: [7 8 9]


In [ ]:
print('Second column:', e[:,1])	

Second column: [5 8]


In [ ]:
## Second Row, two values
print(e[1, :2])

[7 8]


In [ ]:
#Second column 2 values
print(e[:2,1])

[5 8]


In [ ]:
import numpy as np
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)	

[5.15267388 5.54266246 4.98477241 5.25275438 5.10974526 4.48691774
 5.03886423 5.04619826 5.03034109 4.14067777]


In [ ]:
### Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### Median
print(np.median(normal_array))

### Sd
print(np.std(normal_array))

4.140677765979809
5.5426624646131435
4.978560746997366
5.042531241241177
0.37357857546345424


In [ ]:
## Linear algebra
### Dot product: product of two arrays
f = np.array([1,2])
g = np.array([4,5])
### 1*4+2*5
np.dot(f, g)

14

In [ ]:
### Matmul: matruc product of two arrays
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
### 1*5+2*7 = 19
np.matmul(h, i)

array([[19, 22],
       [43, 50]])

In [ ]:
# Taking a 3 * 3 matrix
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
  
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [ ]:
# creating a 2X2 Numpy matrix
n_array = np.array([[50, 29], [30, 44]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the determinant of matrix
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 2X2 matrix:")
print(int(det))

Numpy Matrix is:
[[50 29]
 [30 44]]

Determinant of given 2X2 matrix:
1330


In [ ]:
# Let's create a square matrix (NxN matrix)
mx = np.array([[1,1,1],[0,1,2],[1,5,3]])

# Let's get rank of matrix 
np.linalg.matrix_rank(mx)

3

In [ ]:
example_matrix = np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[ 3.62093727e+01 -2.20937271e+00 -5.14138333e-16 -2.08943529e-15] [[-0.15115432 -0.72704996  0.01790738 -0.26832672]
 [-0.34923733 -0.28320876  0.38415354  0.71367217]
 [-0.54732033  0.16063243 -0.82202921 -0.62236419]
 [-0.74540333  0.60447363  0.41996829  0.17701873]]


In [ ]:
# make matrix with numpy
gfg = np.matrix('[6, 2; 3, 4]')
         
# applying matrix.diagonal() method
diag = gfg.diagonal()
   
print(diag)

[[6 4]]


In [ ]:
# make matrix with numpy
gfg = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.transpose() method
trans = gfg.transpose()
    
print(trans)

[[ 4 12]
 [ 1  3]]


In [ ]:
# make matrix with numpy
gfg = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.trace() method
tracem = gfg.trace()
    
print(tracem)

[[7]]
